### ISSUE TITLE
打开速度比较缓慢

### ISSUE THREAD

**Issue by chung1912** [unilei/image-watermark-tool#4]
build后打开速度也比较缓慢，希望优化

**Comment by unilei** [comment]
是不是国内服务器的问题，vercel部署，打开速度挺快的。

**Comment by chung1912** [comment]
> 是不是国内服务器的问题，vercel部署，打开速度挺快的。

我是本地部署的，打开的时候有时候快有时候慢，似乎是受到连接google、github图标等网络原因引起的

**Comment by unilei** [comment]
> > 是不是国内服务器的问题，vercel部署，打开速度挺快的。
> 
> 我是本地部署的，打开的时候有时候快有时候慢，似乎是受到连接google、github图标等网络原因引起的
图标改成本地加载的了
