### ISSUE TITLE
建议删除所有网络请求功能

### ISSUE THREAD

**Issue by chung1912** [unilei/image-watermark-tool#5]
建议删除所有网络请求功能，把google、cloudflare、github图标（改为本地载入）等相关的网络请求全部去除，实现100%本地运行

**Comment by unilei** [comment]
> 建议删除所有网络请求功能，把google、cloudflare、github图标（改为本地载入）等相关的网络请求全部去除，实现100%本地运行

我不打算打包成exe程序，总归是要联网的，不过这个需求很简单，可以自己修改一下哟~ Bro

**Comment by chung1912** [comment]
> > 建议删除所有网络请求功能，把google、cloudflare、github图标（改为本地载入）等相关的网络请求全部去除，实现100%本地运行
> 
> 我不打算打包成exe程序，总归是要联网的，不过这个需求很简单，可以自己修改一下哟~ Bro

完全本地部署可以没有任何网络连接，速度也会加快，比如https://github.com/joyqi/sfz，速度飞快。不过，你这个UI好看很多

**Comment by unilei** [comment]
> > > 建议删除所有网络请求功能，把google、cloudflare、github图标（改为本地载入）等相关的网络请求全部去除，实现100%本地运行
> > 
> > 
> > 我不打算打包成exe程序，总归是要联网的，不过这个需求很简单，可以自己修改一下哟~ Bro
> 
> 完全本地部署可以没有任何网络连接，速度也会加快，比如https://github.com/joyqi/sfz 速度飞快。不过，你这个UI好看很多
